// <auto-generated />
using Festify.WebRepository.Plan;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Festify.WebRepository.Migrations.Plan
{
    [DbContext(typeof(PlanContext))]
    [Migration("20190930195117_AddedSubmission")]
    partial class AddedSubmission
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Festify.Domain.Plan.Presenter", b =>
                {
                    b.Property<int>("PresenterId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("PresenterId");

                    b.ToTable("Presenter");
                });

            modelBuilder.Entity("Festify.Domain.Plan.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Accepted");

                    b.Property<int>("ConferenceId");

                    b.Property<int>("TalkId");

                    b.HasKey("SubmissionId");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("TalkId");

                    b.ToTable("Submission");
                });

            modelBuilder.Entity("Festify.Domain.Plan.Talk", b =>
                {
                    b.Property<int>("TalkId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abstract")
                        .IsRequired();

                    b.Property<int>("PresenterId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("TalkId");

                    b.HasIndex("PresenterId");

                    b.ToTable("Talk");
                });

            modelBuilder.Entity("Festify.Domain.Plan.Submission", b =>
                {
                    b.HasOne("Festify.Domain.Plan.Talk", "Talk")
                        .WithMany("Submissions")
                        .HasForeignKey("TalkId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Festify.Domain.Plan.Talk", b =>
                {
                    b.HasOne("Festify.Domain.Plan.Presenter", "Presenter")
                        .WithMany("Talks")
                        .HasForeignKey("PresenterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
